### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stong** [Vector35/sigkit#7]
**MVP**
- [x] Double check CRT stuff is included in libgcc (`register_tm_clones` junk like that) #12
- [x] Eliminate false positive from too short signature #8 
- [x] Size issues, how to deliver signatures? #9 
- [x] Performance bug #10 
- [ ] FLIRT conversion #11
- [x] Migrate to binary signature format for better filesize
- [ ] Clean up Python sources (this reop) and release them
- [x] Choose some signature libraries to bundle by default and ship them. Update core.pro to copy them to ui/
- [x] Documentation & blog post

**Enhancements**
- [ ] Windows signature libraries (depends: COFF object file support)
- [ ] Aho-corasick enhancement to linearly scan for functions: improvement to linear sweep
- [ ] Integration with plugin manager system / user contributed signatures? Workflow for managing them?
- [ ] Linker-locality enhancement
- [ ] Sig server where you have automatically generate and share  signatures, enterprises could have private repositories(?)
